version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: kructer
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kructer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

networks:
  postgres_network:

volumes:
  postgres_data: